export const ADD_TO_USER_CARD = 'ADD_TO_USER_CARD'
export const ADD_PRODUCTS_TO_USER_CARD = 'ADD_PRODUCTS_TO_USER_CARD'
export const REMOVE_FROM_USER_CARD = 'REMOVE_FROM_USER_CARD'
export const REMOVE_ALL_PRODUCT = 'REMOVE_ALL_PRODUCT'
export const CLEAR_USER_CARD = 'CLEAR_USER_CARD'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_PROFILE_AVATAR = 'SET_PROFILE_AVATAR'

export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES'
export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES'